# https://medium.com/@aditya.gogoi.30aug/deep-learning-for-predicting-stock-prices-1088534c683f

In [26]:
import pandas as pd
import datetime 
import pandas_datareader.data as web
from pandas import Series, DataFrame
import matplotlib.pyplot as plt
from tensorflow import keras
from tensorflow.keras import metrics
from tensorflow.keras.utils import plot_model
import numpy as np
from tensorflow.keras.layers import Dense 
from tensorflow.keras.layers import LSTM
from tensorflow.keras.layers import SimpleRNN

from tensorflow.keras.models import Sequential


In [16]:
start = datetime.datetime(2015, 1, 1)
end = datetime.datetime.now()

df = web.DataReader('AC.TO', 'yahoo', start , end)
df.head()

High    Low   Open  Close   Volume  Adj Close
Date                                                      
2015-01-02  12.08  11.61  11.93  11.83  1343361      11.83
2015-01-05  12.15  11.83  11.87  12.10  2843480      12.10
2015-01-06  12.13  11.50  12.10  11.75  2121759      11.75
2015-01-07  12.07  11.64  11.90  11.75  1817950      11.75
2015-01-08  12.25  11.80  11.89  12.19  2223888      12.19

In [17]:
training_set = df.iloc[:, 3:4].values
training_set[:10]

array([[11.82999992],
       [12.10000038],
       [11.75      ],
       [11.75      ],
       [12.18999958],
       [12.31000042],
       [12.44999981],
       [12.30000019],
       [11.94999981],
       [11.85000038]])

In [18]:
# https://scikit-learn.org/stable/modules/generated/sklearn.preprocessing.MinMaxScaler.html#sklearn.preprocessing.MinMaxScaler

from sklearn.preprocessing import MinMaxScaler

sc = MinMaxScaler()
training_set = sc.fit_transform(training_set)
training_set[:10]

array([[0.10573078],
       [0.11172813],
       [0.10395379],
       [0.10395379],
       [0.11372722],
       [0.11639272],
       [0.11950244],
       [0.11617059],
       [0.10839626],
       [0.10617504]])

In [19]:
X_train = training_set[:-1]
y_train = training_set[1:]

In [23]:
X_train = np.reshape(X_train, (X_train.shape[0], 1, 1))
X_train[:10]

array([[[0.10573078]],

       [[0.11172813]],

       [[0.10395379]],

       [[0.10395379]],

       [[0.11372722]],

       [[0.11639272]],

       [[0.11950244]],

       [[0.11617059]],

       [[0.10839626]],

       [[0.10617504]]])

In [21]:
model = Sequential()
model.add(LSTM(units = 4, activation = 'sigmoid', input_shape = (None, 1)))
model.add(Dense(units = 1))
model.compile(optimizer = 'adam', loss = 'mean_squared_error')

In [22]:
model.fit(X_train, y_train, batch_size=32, epochs = 200)

Train on 1415 samples
Epoch 1/200
1415/1415 [==============================] - 1s 503us/sample - loss: 0.3284
Epoch 2/200
1415/1415 [==============================] - 0s 42us/sample - loss: 0.2290
Epoch 3/200
1415/1415 [==============================] - 0s 43us/sample - loss: 0.1600
Epoch 4/200
1415/1415 [==============================] - 0s 42us/sample - loss: 0.1147
Epoch 5/200
1415/1415 [==============================] - 0s 44us/sample - loss: 0.0869
Epoch 6/200
1415/1415 [==============================] - 0s 47us/sample - loss: 0.0710
Epoch 7/200
1415/1415 [==============================] - 0s 44us/sample - loss: 0.0624
Epoch 8/200
1415/1415 [==============================] - 0s 44us/sample - loss: 0.0581
Epoch 9/200
1415/1415 [==============================] - 0s 43us/sample - loss: 0.0558
Epoch 10/200
1415/1415 [==============================] - 0s 46us/sample - loss: 0.0543
Epoch 11/200
1415/1415 [==============================] - 0s 47us/sample - loss: 0.0532
Epoch 12/200
1415/

1415/1415 [==============================] - 0s 42us/sample - loss: 3.0773e-04
Epoch 93/200
1415/1415 [==============================] - 0s 42us/sample - loss: 3.0579e-04
Epoch 94/200
1415/1415 [==============================] - 0s 39us/sample - loss: 3.0370e-04
Epoch 95/200
1415/1415 [==============================] - 0s 42us/sample - loss: 3.0148e-04
Epoch 96/200
1415/1415 [==============================] - 0s 42us/sample - loss: 2.9979e-04
Epoch 97/200
1415/1415 [==============================] - 0s 42us/sample - loss: 2.9721e-04
Epoch 98/200
1415/1415 [==============================] - 0s 46us/sample - loss: 2.9543e-04
Epoch 99/200
1415/1415 [==============================] - 0s 43us/sample - loss: 2.9303e-04
Epoch 100/200
1415/1415 [==============================] - 0s 44us/sample - loss: 2.9056e-04
Epoch 101/200
1415/1415 [==============================] - 0s 45us/sample - loss: 2.8881e-04
Epoch 102/200
1415/1415 [==============================] - 0s 46us/sample - loss: 2.8627e-0

1415/1415 [==============================] - 0s 53us/sample - loss: 2.0326e-04
Epoch 181/200
1415/1415 [==============================] - 0s 49us/sample - loss: 2.0424e-04
Epoch 182/200
1415/1415 [==============================] - 0s 50us/sample - loss: 2.0327e-04
Epoch 183/200
1415/1415 [==============================] - 0s 53us/sample - loss: 2.0370e-04
Epoch 184/200
1415/1415 [==============================] - 0s 49us/sample - loss: 2.0527e-04
Epoch 185/200
1415/1415 [==============================] - 0s 44us/sample - loss: 2.0447e-04
Epoch 186/200
1415/1415 [==============================] - 0s 42us/sample - loss: 2.0372e-04
Epoch 187/200
1415/1415 [==============================] - 0s 42us/sample - loss: 2.0198e-04
Epoch 188/200
1415/1415 [==============================] - 0s 43us/sample - loss: 2.0315e-04
Epoch 189/200
1415/1415 [==============================] - 0s 43us/sample - loss: 2.0661e-04
Epoch 190/200
1415/1415 [==============================] - 0s 44us/sample - loss: 2.

In [24]:
model.predict(X_train)

array([[0.10548717],
       [0.11113948],
       [0.10381625],
       ...,
       [0.19201642],
       [0.203435  ],
       [0.19881666]], dtype=float32)

In [28]:
model_rnn = keras.models.Sequential([
    keras.layers.SimpleRNN(4, return_sequences=True, input_shape= (None, 1)),
    keras.layers.SimpleRNN(4, return_sequences=True),
    keras.layers.SimpleRNN(1)
])